### ISSUE TITLE
DLL Error

### ISSUE THREAD

**Issue by cathyadead** [michael-fadely/sadx-dc-lighting#78]
#### Encountered behavior
As soon as i start the game i get an error saying ""Lantern engine dll error %1 is not a valid win 32 application" after this the game loads without lantern engine. i have the dll file needed to run the mod and visual c.

#### Installed mods

 I have every mod featured on the sadx installer along with dreamcast classic textures by sephus jo. disabling everything but lantern engine did not work.

#### Steps to reproduce 
not sure. start the game i guess?

**Comment by PiKeyAr** [comment]
In SADX Mod Manager right click Lantern Engine and select Verify integrity. If any errors come up, let it redownload the mod.
If this doesn't help, check the file d3d8.dll in your SADX folder. It should match this one https://dcmods.unreliable.network/owncloud/data/PiKeyAr/files/Setup/data/d3d8.dll
If the above doesn't help, you might have some issue with your local DirectX 9 installation.

**Comment by cathyadead** [comment]
my direct x isnt working. thanks for the help! ill close this now.
