### ISSUE TITLE
latern engine dosent work and have all the materials

### ISSUE THREAD

**Issue by normaladventure1fan** [michael-fadely/sadx-dc-lighting#80]
hello i really loved playing sonic adventure on the dreamcast when i was a kid i wanted to play with all dreamcast things but everytime i do it it says *latern engine dint work correctly* and i follow the insturctions but that didnt work either (sorry if i had bad english ima spanish* i already have directx12 dll and visualc++ what im doing wrong?

**Comment by PiKeyAr** [comment]
Lantern Engine requires DirectX 9.0c and Visual C++ 2017 runtimes (x86). If you still can't get it to work, try using the [SADX Mod Installer](https://sadxmodinstaller.unreliable.network/).
