### ISSUE TITLE
Rapidly flashing blue light during the Egg Viper boss fight

### ISSUE THREAD

**Issue by ezodagrom** [michael-fadely/sadx-dc-lighting#81]
#### Encountered behavior
Rapidly flashing blue light during the Egg Viper boss fight.

#### Installed mods
* sadx-input-mod
* SteamAchievements
* sadx-dc-lighting (v1.4.9)
* DreamcastConversion (v0.5412)

#### Steps to reproduce:
During the Final Egg boss fight, when the boss is charging the attack that requires for Sonic to use the homing attack across 3 parts of the tail to reach Eggman, the whole screen flashes blue rapidly.
From what I've tried, it only happens when both Dreamcast Conversion and Lantern Engine mods are active together. When either of the mods is not active, this issue doesn't happen.

Image of the blue flash at its brightest:
https://i.imgur.com/gXmrfEl.jpg

**Comment by PiKeyAr** [comment]
It's an effect from the Dreamcast version that was recreated in Dreamcast Conversion.

**Comment by ezodagrom** [comment]
> It's an effect from the Dreamcast version that was recreated in Dreamcast Conversion.
The problem is that the effect is way too strong and hurts in the eyes,
