### ISSUE TITLE
Hyper Knuckles mod black lighting bug

### ISSUE THREAD

**Issue by KirbyClash** [michael-fadely/sadx-dc-lighting#83]
Hey, in the latest version of the Lantern Engine the lighting on Hyper Knuckles with the Hyper Knuckles mod enabled is completely black, this bug was not present before updating the Lantern Engine to the latest version. I have already tested this with all other mods disabled except for the Input Mod that is required for the Hyper Knuckles mod to work as intended, yet this bug is still present. Can this be fixed in the next update?
![Screenshot 2022-10-12 153034](https://user-images.githubusercontent.com/87922883/195431806-cae38411-7862-4f18-9652-436aa506a8e1.png)

**Comment by PiKeyAr** [comment]
It's a known issue that will be fixed in the next update of the Hyper Knuckles mod.

**Comment by KirbyClash** [comment]
> It's a known issue that will be fixed in the next update of the Hyper Knuckles mod.

Thanks.

**Comment by PiKeyAr** [comment]
As far as I know the problem was fixed in version 2.0 of the Hyper Knuckles mod so I'm closing this.
