### ISSUE TITLE
tikal not showing up on sonics intro cutscene

### ISSUE THREAD

**Issue by nathanlycan** [michael-fadely/sadx-dc-lighting#84]
#### Encountered behavior
tikal not showing up in intro cutscene

#### Expected behavior
tikal as glowing orb following the helicopter

#### Installed mods

* sadx-input-mod
* sadx-dc-lighting
* sadx-dc conversion

**Comment by PiKeyAr** [comment]
Thanks for the report. This issue isn't related to the Lantern Engine mod. It's been fixed in DC Conversion.
